export const themes = {
    darkMode: {
      bg: 'bg-gray-900',
      text: 'text-gray-200',
      border: 'border-gray-700',
      cardBg: 'bg-gray-800',
      buttonBg: 'bg-blue-600',
      buttonHover: 'hover:bg-blue-700',
    },
    customMode: {
        bg: 'bg-[#1a202c]',
        text: 'text-[#e2e8f0]',
        border: 'border-[#2d3748]',
        cardBg: 'bg-[#2d3748]',
        buttonBg: 'bg-[#3182ce]',
        buttonHover: 'hover:bg-[#2b6cb0]',
        },
    dracula: {
      bg: 'bg-[#282a36]',
      text: 'text-[#f8f8f2]',
      border: 'border-[#44475a]',
      cardBg: 'bg-[#1e1f29]',
      buttonBg: 'bg-[#ff79c6]',
      buttonHover: 'hover:bg-[#bd93f9]',
    },
    gruvbox: {
      bg: 'bg-[#282828]',
      text: 'text-[#ebdbb2]',
      border: 'border-[#3c3836]',
      cardBg: 'bg-[#3c3836]',
      buttonBg: 'bg-[#fabd2f]',
      buttonHover: 'hover:bg-[#fe8019]',
    },
    nord: {
      bg: 'bg-[#2e3440]',
      text: 'text-[#d8dee9]',
      border: 'border-[#4c566a]',
      cardBg: 'bg-[#3b4252]',
      buttonBg: 'bg-[#81a1c1]',
      buttonHover: 'hover:bg-[#5e81ac]',
    },
    oneDark: {
      bg: 'bg-[#282c34]',
      text: 'text-[#abb2bf]',
      border: 'border-[#4b5263]',
      cardBg: 'bg-[#2c323c]',
      buttonBg: 'bg-[#61afef]',
      buttonHover: 'hover:bg-[#528bff]',
    },
    cobalt: {
      bg: 'bg-[#002240]',
      text: 'text-[#ffffff]',
      border: 'border-[#0e4b82]',
      cardBg: 'bg-[#002b56]',
      buttonBg: 'bg-[#ff9800]',
      buttonHover: 'hover:bg-[#ff5722]',
    },
  };